### ISSUE TITLE
I can't start the program

### ISSUE THREAD

**Issue by SweydManaf** [rohankishore/Aura-Text#1]
1. First i get this bug then i fixed
```
menubar = Menu(coding, background='blue', fg='white')
    ^
IndentationError: expected an indented block after function definition on line 670
```
2. When i tryed to run i got this new problem and i don't know what lib you want to import
```
ModuleNotFoundError: No module named 'idlelib', line 9
```

**Comment by rohankishore** [comment]
Can you please try it again? Because it's all fine on my system. And also, you are getting the 'idlelib' error because idlelib is not an inbuilt python module (like webbrowser, random, math etc...) in Linux (I'm pretty sure that you're using Linux else this issue wouldn't come)
As I said above, I've made some changes to the app and updated the GitHub code too... Kindly try running the new version... And if you wanna install 'idlelib' as an external library, just run 
```bash
sudo apt install idle3
```

 If the issue still persists, then contact me at [Instagram](www.instagram.com/jops.niqqa/). Also if you liked my project, then kindly give me a star!
