### ISSUE TITLE
do not have requitments.txt and can not run on windows

### ISSUE THREAD

**Issue by NothinkingGao** [rohankishore/Aura-Text#26]
do not have requitments.txt file,can not run on windows.can you add it and make the code can run on windows.

**Comment by rohankishore** [comment]
Hi @NothinkingGao. `Requirements.txt` file has been added to the `auratext` folder. Anyways, there's only 2 libraries you'll need to install separately. Remaining all libs are prebuilt ones.

- Pyttsx3 (For TTS) `pip install pyttsx3`
- PySide6 (For GUI) `pip install PySide6`

If you don't have any other problems, reply with a smiley emoji so that i can close this issue. You can make another Issues thread if you face anything later.

Thanks
Rohan
