### ISSUE TITLE
No AuraText.exe[BUG]

### ISSUE THREAD

**Issue by rfischer85** [rohankishore/Aura-Text#29]
Hi, I saw your post on Reddit and thought I'd like to try this.
The README.md says to download the auratext.exe, but there isn't a file in the releases folder.
I also got a bug trying to run it as a developer.

# Bug

## Describe the bug
Runnig "python AuraText.py" in the terminal gives me a "ModuleNotFoundError"

<br>

## Screenshots
![Screenshot 2023-08-02 220557](https://github.com/rohankishore/Aura-Text/assets/122385079/c7d7a38d-fedd-431d-b9c3-33570b5c463b)

## Desktop Specs
 - OS: Windows 11 22H2 
 - Aura Text Version: 4.2

**Comment by rohankishore** [comment]
It's because you haven't installed the git modules and Git. If I'm right, you just need the module to use Aura Text but you'll need Git PC App to clone GitHub repos.

To install git module, `pip install GitPython` will do the trick most probably. To use the "Clone Project from Git" feature, you'll need Git installed on your PC. Download Git from here: https://git-scm.com/download/win
